version: '3.8'
services:
  app:
    build: ..
    volumes:
      - ..:/app
    ports:
      - '8000:8000'
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHROMA_PERSIST_DIR=/app/chroma_data
